# Generated by cucumber-sinatra. (2017-11-18 17:53:16 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/todo_web.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = TodoWeb::App

class TodoWebWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TodoWebWorld.new
end
