# Generated by cucumber-sinatra. (2017-11-18 17:53:16 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/todo_web.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Before do
  @real_home = ENV['HOME']
  fake_home = File.expand_path(File.join('tmp/', 'fake_home'))
  ENV['HOME'] = fake_home
  FileUtils.mkpath(fake_home)
end

After do
  ENV['RUBYLIB'] = @original_rubylib
  ENV['HOME'] = @real_home
end

Capybara.app = TodoWeb::App

class TodoWebWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TodoWebWorld.new
end
