# Generated by cucumber-sinatra. (2017-11-18 17:53:16 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/todo_web.rb')

require 'capybara'
require 'capybara/cucumber'
require 'todo'

Before do
  @real_home = ENV['HOME']
  fake_home = File.expand_path(File.join('tmp/', 'fake_home'))
  FileUtils.rm_rf(fake_home) if Dir.exist?(fake_home)
  ENV['HOME'] = fake_home
  FileUtils.mkpath(fake_home)
  Todo::UseCases::SetCurrentDay.new(new_day: 'today').perform
end

After do
  ENV['RUBYLIB'] = @original_rubylib
  ENV['HOME'] = @real_home
end

Capybara.app = TodoWeb::App

class TodoWebWorld
  include Capybara::DSL
end

World do
  TodoWebWorld.new
end
